const types = {
    DATE_MODAL_OPEN: 'DATE_MODAL_OPEN',
    DATE_MODAL_CLOSE: 'DATE_MODAL_CLOSE',
    STARTDATE_MODAL_CHANGE: 'STARTDATE_MODAL_CHANGE',
    ENDDATE_MODAL_CHANGE: 'ENDDATE_MODAL_CHANGE',
    STARTDATE_MODAL_ACTION: 'STARTDATE_MODAL_ACTION',
    ENDDATE_MODAL_ACTION: 'ENDDATE_MODAL_ACTION',
  };
  
  export default types;